name: pip-installer

on:
  push:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Pip Installer
      uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt

              
         
                
