name: Pytest

on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["pip-install"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Pip Installer
      uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt

    - name: Run pytest
      run: |
        pip install pytest
        pytest -s app/src/test/
