name: Pytest

on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["pip-install"]
    types:
      - completed
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Run pytest
      run: |
        pip install pytest
        pytest -s app/src/test/