# Slack Decision Test 워크플로우
name: Slack Decision Test

on:
  workflow_run:
    workflows: ["Pytest"]
    types:
      - completed

jobs:
  decision-test:
    runs-on: ubuntu-latest

    steps:
      - name: Output decision
        if: ${{ github.event.inputs.decision == 'yes' }}
        run: echo "You selected YES, proceeding with deployment."

      - name: No action for NO
        if: ${{ github.event.inputs.decision == 'no' }}
        run: echo "You selected NO, workflow will end."